FROM bde2020/spark-worker:2.1.0-hadoop2.7

ADD zookeeper-3.5.2-alpha.tar.gz /usr/local/apache-zookeeper/
RUN ln -s /usr/local/apache-zookeeper/zookeeper-3.5.2-alpha /usr/local/apache-zookeeper/current
RUN rm -f /tmp/zookeeper-3.5.2-alpha.tar.gz


